#!/usr/bin/env bash

mygreeting=Hello
mygreeting2="Good Morning"
number=16
echo $mygreeting
echo $mygreeting2
echo $number

myvar="Hello!"
echo "The valye of the myvar variable is: $myvar"
myvar="Cool"
echo "The valye of the myvar variable is: $myvar"

declare -r myname="Scott"
echo "The valye of the myname variable is: $myname"
myname="Scootp"
echo "The valye of the myname variable is: $myname"


declare -l lowerstring="This is some TEXT!"
echo "The value of the lowerstring variable is: $lowerstring"
lowerstring="Let's CHANGE the VALUE!"
echo "The value of the lowerstring variable is: $lowerstring"

declare -u upperstring="This is some TEXT!"
echo "The value of the upperstring variable is: $upperstring"
upperstring="Let's CHANGE the VALUE!"
echo "The value of the upperstring variable is: $upperstring"